version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - apt update
      - apt install -y nodejs npm nodejs-dev node-gyp libssl1.0-dev
      - npm install
  build:
    commands:
      - npm test
