version: 0.2

phases:
  install:
    commands:
      - apt update
      - apt install -y nodejs npm nodejs-dev node-gyp libssl1.0-dev
      - npm install
  build:
    commands:
      - npm test

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on  running npm 
			- npm install
			- echo Build started on `date` running ./cli2.sh
      - ./cli2.sh
  post_build:
    commands:
      - echo Build completed on `date`